"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const roomController_1 = require("../controllers/roomController");
const authMiddleware_1 = require("../middleware/authMiddleware");
const asyncHandler_1 = require("../middleware/asyncHandler");
const router = (0, express_1.Router)();
router.post("/", (0, asyncHandler_1.asyncHandler)(authMiddleware_1.protect), (0, asyncHandler_1.asyncHandler)(roomController_1.createRoom));
router.get("/:id", (0, asyncHandler_1.asyncHandler)(roomController_1.getRoom));
router.post("/:id/vote", (0, asyncHandler_1.asyncHandler)(roomController_1.voteRoom));
router.get("/:id/results", (0, asyncHandler_1.asyncHandler)(authMiddleware_1.protect), (0, asyncHandler_1.asyncHandler)(roomController_1.getResults));
exports.default = router;
